# Generated by Django 4.2.7 on 2024-01-18 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id_anime', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_ingles', models.CharField(max_length=30)),
                ('titulo_japones', models.CharField(max_length=30)),
                ('synopsis', models.TextField()),
                ('cantidad_episodios', models.IntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('puntuacion', models.FloatField()),
                ('popularidad', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('year_of_release', models.IntegerField()),
                ('imagen_url', models.CharField(max_length=80)),
                ('fecha_de_estreno', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'anime',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('url_descripcion', models.TextField()),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id_personaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('url_imagen_personaje', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'personaje',
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id_productor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('nombre_japones', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('url_sitio_web', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'productor',
            },
        ),
        migrations.CreateModel(
            name='lista_favoritos',
            fields=[
                ('id_lista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lista', models.CharField(max_length=40)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_de_modificacion', models.DateField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_animes', models.IntegerField()),
                ('categoria_genero', models.CharField(max_length=40)),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_favoritos', to=settings.AUTH_USER_MODEL)),
                ('nombres_animes', models.ManyToManyField(related_name='lista_favoritos', to='main.anime')),
            ],
            options={
                'db_table': 'lista_favoritos',
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id_episodio', models.AutoField(primary_key=True, serialize=False)),
                ('numero_episodio', models.IntegerField()),
                ('titulo_episodio', models.CharField(max_length=40)),
                ('titulo_en_japones', models.CharField(max_length=80)),
                ('animes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodio', to='main.anime')),
            ],
            options={
                'db_table': 'episodio',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='generos_id',
            field=models.ManyToManyField(related_name='genero', to='main.genero'),
        ),
        migrations.AddField(
            model_name='anime',
            name='personajes_id',
            field=models.ManyToManyField(related_name='personaje', to='main.personaje'),
        ),
        migrations.AddField(
            model_name='anime',
            name='productores_id',
            field=models.ManyToManyField(related_name='productor', to='main.productor'),
        ),
    ]
