# Generated by Django 4.2.7 on 2024-01-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_anime_titulo_japones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='titulo_episodio',
            field=models.CharField(max_length=80),
        ),
    ]
