# Generated by Django 4.2.7 on 2024-01-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_episodio_titulo_episodio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
