# Generated by Django 4.2.7 on 2024-02-06 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_alter_episodio_titulo_episodio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Anime'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterModelOptions(
            name='lista_favoritos',
            options={'verbose_name': 'Lista de favoritos', 'verbose_name_plural': 'Listas de favoritos'},
        ),
        migrations.AlterModelOptions(
            name='productor',
            options={'verbose_name_plural': 'Productores'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='cantidad_episodios',
            field=models.IntegerField(verbose_name='Cantidad de episodios'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='id_anime',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='titulo_ingles',
            field=models.CharField(max_length=80, verbose_name='Título en inglés'),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='animes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodio', to='main.anime', verbose_name='Anime al que le pertenece'),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='titulo_episodio',
            field=models.CharField(max_length=255, verbose_name='Título del episodio'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=80, verbose_name='Nombre del género'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='url_descripcion',
            field=models.TextField(verbose_name='Link de la descripción'),
        ),
        migrations.AlterField(
            model_name='lista_favoritos',
            name='cantidad_animes',
            field=models.IntegerField(verbose_name='Cantidad de animes'),
        ),
        migrations.AlterField(
            model_name='lista_favoritos',
            name='categoria_genero',
            field=models.CharField(max_length=40, verbose_name='Categoría de género'),
        ),
        migrations.AlterField(
            model_name='lista_favoritos',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la lista'),
        ),
        migrations.AlterField(
            model_name='lista_favoritos',
            name='id_lista',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lista_favoritos',
            name='nombre_lista',
            field=models.CharField(max_length=40, verbose_name='Nombre de la lista'),
        ),
        migrations.AlterField(
            model_name='lista_favoritos',
            name='nombre_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_favoritos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='lista_favoritos',
            name='nombres_animes',
            field=models.ManyToManyField(related_name='lista_favoritos', to='main.anime', verbose_name='Animes que incluye'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del personaje'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='url_sitio_web',
            field=models.CharField(max_length=80, verbose_name='Link del sitio web'),
        ),
    ]
