# Generated by Django 4.2.7 on 2024-02-06 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_alter_anime_options_alter_genero_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='anime',
            name='create_by_community',
            field=models.BooleanField(default=False, verbose_name='Creado por la comunidad'),
        ),
    ]
