# Generated by Django 4.2.7 on 2024-02-09 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_anime_create_by_anime_create_by_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
